# Generated by Django 4.1.5 on 2023-01-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_nationalities_movies_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='summary',
            field=models.TextField(help_text='Escribe un breve resumen', max_length=150, null=True),
        ),
    ]
